"""adding default adress

Revision ID: 2acf4ff9c60a
Revises: 3e7897bc5efd
Create Date: 2023-06-19 19:14:51.315665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acf4ff9c60a'
down_revision = '3e7897bc5efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), server_default='N/A', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
