"""adding author relationship

Revision ID: 95189f66b139
Revises: d4a678fff3d2
Create Date: 2023-06-19 19:40:34.391374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95189f66b139'
down_revision = 'd4a678fff3d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=True),
    sa.Column('lname', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('helper',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], )
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('genre')
        batch_op.drop_column('author')

    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=100), server_default=sa.text("'N/A'"), nullable=False))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(length=50), nullable=True))

    op.drop_table('helper')
    op.drop_table('authors')
    # ### end Alembic commands ###
